# Generated by Django 4.2.2 on 2023-07-08 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userAuth', '0001_initial'),
        ('CoursesApp', '0001_initial'),
        ('TestsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(to='userAuth.student', verbose_name='Студенты'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='groups',
            field=models.ManyToManyField(to='CoursesApp.group'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='tests',
            field=models.ManyToManyField(to='TestsApp.test'),
        ),
    ]
