# Generated by Django 4.2.2 on 2023-07-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.TextField(max_length=127, verbose_name='Название курса'),
        ),
    ]
