# Generated by Django 4.2.2 on 2023-07-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0005_alter_course_options_alter_coursetest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='index',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
