# Generated by Django 4.2.2 on 2023-07-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0006_group_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetest',
            name='date_expired',
        ),
    ]
