# Generated by Django 4.2.2 on 2023-07-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=255, verbose_name='Вариант ответа')),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=255, verbose_name='Вопрос')),
                ('max_points', models.PositiveIntegerField()),
                ('qtype', models.CharField(choices=[('single', 'Single'), ('mutiple', 'Multiple')], default='single', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=127, verbose_name='Название теста')),
                ('description', models.TextField(max_length=255, verbose_name='Описание')),
                ('count', models.IntegerField(verbose_name='Количество вопросов')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('date_expired', models.DateTimeField(auto_now=True, verbose_name='Дата истекания доступа к тесту')),
                ('test_time', models.TimeField()),
                ('max_result', models.IntegerField()),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ('time_update', 'title'),
            },
        ),
    ]
