# Generated by Django 4.2.2 on 2023-07-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('студент', 'Student'), ('автор', 'Author'), ('преподаватель', 'Teacher')], default='студент', max_length=50, verbose_name='Роль'),
        ),
    ]
