# Generated by Django 4.2.2 on 2023-07-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0003_alter_course_title'),
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='+', to='CoursesApp.course', verbose_name='Курсы студента'),
        ),
    ]
