# Generated by Django 4.2.2 on 2023-07-07 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentApp', '0001_initial'),
        ('userAuth', '0001_initial'),
        ('authorApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.student'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorApp.test'),
        ),
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorApp.answer'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorApp.question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.student'),
        ),
    ]
