# Generated by Django 4.2.2 on 2023-07-08 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userAuth', '0001_initial'),
        ('TestsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.author'),
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='+', to='TestsApp.question', verbose_name='Вопросы'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.student'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestsApp.test'),
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='+', to='TestsApp.answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestsApp.test'),
        ),
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestsApp.answer'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestsApp.question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.student'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestsApp.question'),
        ),
    ]
