# Generated by Django 4.2.2 on 2023-07-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestsApp', '0004_studentresult_is_passed_test_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='date_expired',
        ),
        migrations.RemoveField(
            model_name='test',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_time',
        ),
    ]
