# Generated by Django 4.2.2 on 2023-07-14 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0007_remove_coursetest_date_expired'),
        ('TestsApp', '0006_alter_question_qtype_alter_test_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CoursesApp.group'),
        ),
    ]
