# Generated by Django 4.2.2 on 2023-07-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestsApp', '0007_studentresult_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='group',
        ),
    ]
