# Generated by Django 4.2.2 on 2023-07-16 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0007_remove_coursetest_date_expired'),
        ('TestsApp', '0011_choice_student_result_studentresult_choises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='group',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CoursesApp.course'),
        ),
    ]
